name: Pull requests

on:
  pull_request_target:
    branches:
      - 'master'

jobs:

  verify:
    name: Verify ${{ matrix.os }} jdk${{ matrix.java }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        java: [ 8, 11, 13 ]
        exclude:
          - os: ubuntu-latest
            java: 11

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: 'refs/pull/${{ github.event.number }}/merge'

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ matrix.os }}-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.os }}-jdk${{ matrix.java }}-

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          sonatypeSnapshots: true

      - run: mvn verify

  sonar:
    name: Verify Sonar ubuntu-latest jdk11

    needs: verify

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: 'refs/pull/${{ github.event.number }}/merge'
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ubuntu-latest-jdk11-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-jdk11-

      - uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: sonar-cache
          restore-keys: sonar-cache

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          sonatypeSnapshots: true

      - run: mvn verify

      - run: mvn sonar:sonar -Dsonar.verbose=true
        if: github.repository_owner == 's4u'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
